import "/src/app/globals.css";
import type { Metadata } from "next";
import { Kodchasan } from "next/font/google";
import { Providers } from "./providers";
import Login from "../../pages/Login";
import Nav from "@/components/Nav";

const kodchasan = Kodchasan({
   subsets: ["latin"],
   weight: ["400", "700"],
});

export const metadata: Metadata = {
   title: "My Pos",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={kodchasan.className}>
            <Providers>
               <Nav onAddData={function (item: any): void {
                  throw new Error("Function not implemented.");
               } } onSubData={function (item: any): void {
                  throw new Error("Function not implemented.");
               } } onDeleteData={function (item: number): void {
                  throw new Error("Function not implemented.");
               } } onResetData={function (): void {
                  throw new Error("Function not implemented.");
               } } items={undefined} sumPrice={0} />
               <Login />
            </Providers>
         </body>
      </html>
   );
}
