import "/src/app/globals.css";
import type { Metadata } from "next";
import { Kodchasan } from "next/font/google";
import { Providers } from "./providers";
import Login from "../../pages/Login";

const kodchasan = Kodchasan({
   subsets: ["latin"],
   weight: ["400", "700"],
});

export const metadata: Metadata = {
   title: "My Pos",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={kodchasan.className}>
            <Providers>
               <Login />
            </Providers>
         </body>
      </html>
   );
}
